bpe_tokenizer:
  bpe: sentencepiece
  sentencepiece_model: /home/data_ti6_c/wangdq/data/ST/ende/st_vocab.model
src_bpe_tokenizer:
  bpe: sentencepiece
  sentencepiece_model: /home/data_ti6_c/wangdq/data/ST/ende/asr_vocab.model
input_channels: 1
input_feat_per_channel: 80
sampling_alpha: 1.0
specaugment:
  freq_mask_F: 27
  freq_mask_N: 1
  time_mask_N: 1
  time_mask_T: 100
  time_mask_p: 1.0
  time_wrap_W: 0
transforms:
  '*':
    - utterance_cmvn
  _train:
    - utterance_cmvn
    - specaugment
vocab_filename: /home/data_ti6_c/wangdq/data/ST/ende/st_vocab.txt
src_vocab_filename: /home/data_ti6_c/wangdq/data/ST/ende/asr_vocab.txt
tgt_field: tgt_text
data:

