export CUDA_VISIBLE_DEVICES=$1
fairseq-train /home/data_ti6_c/wangdq/data/ST/large/MT/test/ \
  --arch transformer_256 --share-decoder-input-output-embed \
  --encoder-embed-dim 256 --decoder-embed-dim 256 \
  --encoder-attention-heads 4 --decoder-attention-heads 4 \
  --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
  --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 \
  --dropout 0.3 --weight-decay 0.0001 \
  --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
  --max-tokens 4096 \
  --eval-bleu \
  --eval-bleu-args '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}' \
  --eval-bleu-detok moses \
  --eval-bleu-remove-bpe "sentencepiece" \
  --best-checkpoint-metric bleu --maximize-best-checkpoint-metric \
  --keep-best-checkpoints 5 \
  --no-epoch-checkpoints \
  -s en -t de \
  --tensorboard-logdir /home/wangdq/tensorboard/ST/end2end/ \
  --save-interval-updates 500 --keep-interval-updates 1 \
  --save-dir /home/wangdq/save/mt_test/ \
  --bpe sentencepiece --sentencepiece-model /home/data_ti6_c/wangdq/data/ST/ende/st_vocab.model
